Django==1.11
django-fieldbook
#fieldbook_py # it gives "RuntimeError: maximum recursion depth exceeded"